### ISSUE TITLE
Embed Info Request

### ISSUE THREAD

**Issue by tjmoses** [seeratawan01/vue-lazytube#1]
Good library, and this saved me from writing the same code myself. I do recommend adding the option to not load embed information on mount b/c some (such as myself w/ vimeo) just want to 100% lazy load the iframe video with no initial requests. Also it appears you have a generated dist folder in the Repo.

**Comment by seeratawan01** [comment]
@tjmoses thanks for suggestion, I'll look into this in the upcoming release.

**Comment by seeratawan01** [comment]
You can achieve it using 'oembedFetch' prop by setting it to false
