### ISSUE TITLE
Vimeo - Wrong Thumbnail vs Vimeo Embedded Code 

### ISSUE THREAD

**Issue by Tragio** [seeratawan01/vue-lazytube#13]
Hello @seeratawan01,

Thank you for your amazing work.

**Describe the bug**
Vue LazyTube is showing the wrong Vimeo thumbnail.

![Screenshot 2021-05-12 at 09 55 51](https://user-images.githubusercontent.com/5109593/117947608-442f6880-b308-11eb-805d-30e881e6ac48.jpg)

**To Reproduce**
You can test with this link https://player.vimeo.com/video/546019197

Thank you very much!

**Comment by Tragio** [comment]
@seeratawan01 the code is assuming that the thumbnail is the same ID as the video, however, that's not correct.

One way to retrieve the correct thumbnail is to fetch the following:

`https://vimeo.com/api/oembed.json?url=https://vimeo.com/546019197`

To retrieve the correct thumbnail ID and still use the `quality_key`.

**Comment by finex** [comment]
Hi, I've also experienced this bug.

**Comment by zaosoula** [comment]
Hello, now the bug is even worst no thumbnail is displayed. I found a way to fetch it using the Vimeo API v2 and implement it into this PR #19. If you have time to check or even improve it, it will be appreciated.

**Comment by seeratawan01** [comment]
Fixed
