### ISSUE TITLE
Init fail

### ISSUE THREAD

**Issue by Jakevin** [seeratawan01/vue-lazytube#8]
**Describe the bug**
When start project. The console will show this error
Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

**Screenshots**
![截圖 2021-05-09 上午1 16 35](https://user-images.githubusercontent.com/4224127/117547802-35c12280-b064-11eb-843d-fc921d310b58.png)

**Desktop (please complete the following information):**
 - OS: macOS big sur
 - Browser chrome
 - Version 90.0.4430.93

**Additional context**
Vue version: 3.0.5

**Comment by seeratawan01** [comment]
@Jakevin this component is compatible with vue 2.
